name: finki-hub-mcp-dev

networks:
  finki_stack_dev:
    driver: bridge
    name: finki_stack_dev
    # Set external to true to use an existing network
    # external: true

services:
  local-mcp:
    build:
      context: ./local-mcp
    environment:
      DATA_STORAGE_URL: ${DATA_STORAGE_URL}
    image: finki-hub/mcp-local:latest
    networks:
      - finki_stack_dev
    ports:
      - "8808:8808"
    pull_policy: never
    restart: unless-stopped
