name: finki-hub-mcp-dev

networks:
  finki_stack_dev:
    driver: bridge
    name: finki_stack_dev
    # Set external to true to use an existing network
    # external: true

services:
  local-mcp:
    build:
      context: ./local-mcp
    image: finki-hub/mcp-local:latest
    networks:
      - finki_stack_dev
    ports:
      - '8808:8808'
    pull_policy: never
    restart: unless-stopped
    volumes:
      - ./data:/data
